version: '3.7'

services:
  app:
    image: webdevops/php-nginx:7.4
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: 1
  database:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - '8080:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: bitnami
    volumes:
      - 'rabbitmq_data:/bitnami'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
volumes:
  mysql_data:
    driver: local
  rabbitmq_data:
    driver: local
